List<String> envTips = [
  "Use a rain barrel to collect water for gardening.",
  "Choose bamboo products over plastic to reduce waste.",
  "Install a greywater system to reuse household water.",
  "Create a habitat for bees with native plants.",
  "Opt for hand-powered tools over electric ones.",
  "Make eco-bricks with non-recyclable plastics.",
  "Support companies with sustainable practices.",
  "Start a community garden to share resources.",
  "Use wool dryer balls to save energy.",
  "Choose low-VOC paints for home projects.",
  "Use a push mower instead of a gas mower.",
  "Install a bat house to control pests naturally.",
  "Choose organic cotton clothing.",
  "Use soap nuts for natural laundry cleaning.",
  "Switch to digital receipts and avoid paper waste.",
  "Repurpose glass jars for storage.",
  "Support renewable energy projects.",
  "Practice xeriscaping to reduce water use.",
  "Buy biodegradable cleaning products.",
  "Use a solar charger for devices.",
  "Create a worm bin for composting.",
  "Choose furniture made from reclaimed wood.",
  "Use natural fiber sponges for cleaning.",
  "Opt for plant-based milks and reduce dairy.",
  "Invest in a reusable coffee filter.",
  "Make homemade natural air fresheners.",
  "Use a programmable slow cooker for energy savings.",
  "Buy in bulk to reduce packaging waste.",
  "Install low-flow showerheads and faucets.",
  "Create an eco-friendly gift wrapping station."
];
